// src/pages/index.js
import React from 'react';

export default function Contact() {
  return (
    <div>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mattis lectus eget turpis vulputate, quis porttitor justo rhoncus. Pellentesque id neque vel lacus laoreet mollis ut sed enim. Pellentesque fermentum lacinia tincidunt. Maecenas dui turpis, vestibulum eget odio vel, lacinia tincidunt orci. Maecenas a enim ut magna ornare scelerisque imperdiet in nunc. Integer sapien justo, cursus in mollis id, mollis quis elit. Proin consectetur lorem eget ante malesuada, condimentum tempor ante congue.</p>
      <p>Vestibulum elementum sem ut ipsum porttitor, at rhoncus sapien iaculis. Pellentesque mollis eleifend nunc sed congue. In lectus enim, rhoncus ac nibh at, pharetra blandit nulla. Vivamus malesuada ante id magna dictum commodo. Quisque quis diam ut ipsum dapibus maximus. Ut vel risus ut purus eleifend venenatis. Nunc mattis diam lacus, et aliquam orci aliquet et. Cras et massa vel arcu scelerisque consequat. Mauris in dictum nunc, egestas venenatis ligula. Donec at mi sed quam rutrum lobortis quis ac felis. Praesent at enim non turpis scelerisque sagittis id et felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas id dui non nunc consequat malesuada. Mauris non eleifend magna.</p>
      <p>Phasellus tempus vitae libero quis faucibus. Praesent vulputate at quam nec maximus. Donec non tincidunt ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin id massa sit amet erat lobortis hendrerit ac sit amet dolor. Sed tincidunt aliquam molestie. Praesent tellus arcu, interdum id ex eu, ornare rhoncus nisl. Suspendisse potenti. Fusce lorem turpis, commodo eu venenatis quis, euismod sit amet lacus. Donec dictum sapien et turpis semper, vitae porta purus fermentum. Sed imperdiet, mauris sed tempus luctus, massa sem semper lectus, ac varius erat tortor eget nisl. Suspendisse potenti. Praesent consectetur dapibus facilisis. Quisque euismod pharetra urna a convallis. Donec quis ornare enim. Vestibulum condimentum finibus libero, cursus mattis ipsum tincidunt sit amet.</p>
      <p>Curabitur scelerisque magna ac leo vehicula, id bibendum risus aliquet. Suspendisse eget odio mi. Etiam nisi justo, pellentesque eget arcu vitae, malesuada sodales ex. In sed pharetra libero, sed tincidunt velit. Curabitur lobortis feugiat dictum. Integer quis posuere ipsum. Aliquam ac orci tempus, iaculis neque nec, luctus ipsum. Cras ut placerat elit. Aenean eu posuere urna. Cras tincidunt vitae tellus sit amet pretium. Maecenas mattis odio a dignissim commodo. Sed posuere efficitur elit, eu accumsan metus tincidunt sed. Vestibulum sed nulla nunc. Quisque pretium quam eu lacus finibus, et rhoncus augue rutrum.</p>
      <p>Pellentesque pellentesque dolor vel ante dapibus luctus. Phasellus quis felis nec eros vestibulum elementum sit amet in libero. Proin venenatis dui non pharetra egestas. Quisque ullamcorper at mi ut sodales. Aliquam interdum ligula quis porttitor auctor. Duis volutpat, metus vitae gravida sollicitudin, nisl eros ullamcorper turpis, nec pharetra quam justo id sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed dui non eros consequat euismod. In hac habitasse platea dictumst. Integer ultricies eros non sem molestie imperdiet vitae eget erat. Mauris rhoncus dui id mollis facilisis. Pellentesque lacinia tristique risus vel dictum. Suspendisse potenti. </p>
    </div>
  );
}
